### ISSUE TITLE
Problem building with Julia v0.5 

### ISSUE THREAD

**Issue by slwu89** [johnmchambers/juliaExamples#1]
<img width="670" alt="screenshot 2017-02-01 11 25 28" src="https://cloud.githubusercontent.com/assets/10673535/22522713/8b73ffdc-e871-11e6-989b-da01dc8ee94d.png">

I downloaded the repo and attempted to use devtools "load_all" command to test the XR interface, however the package does not successfully load because it appears that it cannot assign objects to the namespace for some reason.

Device info:
R: 3.2.2
RStudio: 1.0.136
Julia: v0.5

**Comment by johnmchambers** [comment]
Clearly, there seem to be problems with Julia 0.5.  I don't have that version currently.  Will look into it but can't promise a time frame, other things in the way right now.

A report from a standard R CMD build/INSTALL might give a different message.

On Feb 1, 2017, at 11:31 AM, Sean Wu <notifications@github.com<mailto:notifications@github.com>> wrote

[screenshot 2017-02-01 11 25 28]<https://cloud.githubusercontent.com/assets/10673535/22522713/8b73ffdc-e871-11e6-989b-da01dc8ee94d.png>

I downloaded the repo and attempted to use devtools "load_all" command to test the XR interface, however the package does not successfully load because it appears that it cannot assign objects to the namespace for some reason.

Device info:
R: 3.2.2
RStudio: 1.0.136
Julia: v0.5

**Comment by slwu89** [comment]
@johnmchambers Thanks for the update! Unfortunately I got the same error when doing a build from the terminal. Definitely looking forward to updates for XRJulia; thanks for the package and the Extending R book.
